// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
import React, { createContext, useState } from 'react';

interface LivePreviewContextType {
  previewData: unknown;
  setPreviewData: React.Dispatch<React.SetStateAction<unknown>>;
}

export const LivePreviewContext = createContext<LivePreviewContextType | null>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [previewData, setPreviewData] = useState<unknown>(null);

  return (
    <html lang="en">
      <body>
        {/* Provide context to all children */}
        <LivePreviewContext.Provider value={{ previewData, setPreviewData }}>
          {children}
        </LivePreviewContext.Provider>
      </body>
    </html>
  );
}
